# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Message:
  fields:
    default: email, message
    form: email, message
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: bootyard

